version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - "db_volume:/var/lib/mysql"

  rabbit:
    image: rabbitmq:3-management
    expose:
      - "5672"
    ports:
      - "${RABBITMQ_PORT}:15672"
    env_file: .env
    volumes:
      - "rabbitmq_volume:/var/lib/rabbitmq"

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    env_file: .env
    ports:
      - "${XDEBUG_PORT}:9003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - rabbit
      - db
    volumes:
      - "./app:/app"
      - "./docker/app/php.${APP_ENV}.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    command: "php-fpm"

  front:
    image: nginx:1.25.2-bookworm
    env_file: .env
    ports:
      - "${FRONT_PORT}:80"
    links:
      - app
    volumes:
      - "./app:/app"
      - "./docker/app/php.${APP_ENV}.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
      - "./docker/front/nginx.${APP_ENV}.conf:/etc/nginx/conf.d/default.conf:ro"

volumes:
  db_volume:
    driver: local
  rabbitmq_volume:
    driver: local
