# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
  - { resource: services/ }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Application\:
      resource: '../src/Application'
      exclude:
          - '../src/Application/Query/'
          - '../src/Application/Command/'
          - '../src/Application/UseCase/'

    Domain\:
        resource: '../src/Domain'
        exclude:
            - '../src/Domain/*/Entity/'

    Infrastructure\:
        resource: '../src/Infrastructure'
        exclude:
          - '../src/Infrastructure/Doctrine/Migration/'
          - '../src/Infrastructure/Twig/templates/'
          - '../src/Infrastructure/Twig/assets/'
