framework:
    messenger:
#        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'
#            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
